package fridge;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import fridge.FridgeItem;
import fridge.InFridge;
import fridge.History;

import fridge.FridgeItemDao;
import fridge.InFridgeDao;
import fridge.HistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fridgeItemDaoConfig;
    private final DaoConfig inFridgeDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final FridgeItemDao fridgeItemDao;
    private final InFridgeDao inFridgeDao;
    private final HistoryDao historyDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fridgeItemDaoConfig = daoConfigMap.get(FridgeItemDao.class).clone();
        fridgeItemDaoConfig.initIdentityScope(type);

        inFridgeDaoConfig = daoConfigMap.get(InFridgeDao.class).clone();
        inFridgeDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        fridgeItemDao = new FridgeItemDao(fridgeItemDaoConfig, this);
        inFridgeDao = new InFridgeDao(inFridgeDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(FridgeItem.class, fridgeItemDao);
        registerDao(InFridge.class, inFridgeDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        fridgeItemDaoConfig.getIdentityScope().clear();
        inFridgeDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
    }

    public FridgeItemDao getFridgeItemDao() {
        return fridgeItemDao;
    }

    public InFridgeDao getInFridgeDao() {
        return inFridgeDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
