package fridge;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FRIDGE_ITEM.
 */
public class FridgeItem {

    private Long internalId;
    private Long barcode;
    private Long avg_haltbarkeit;
    private Long times_changed;
    private String name;

    public FridgeItem() {
    }

    public FridgeItem(Long internalId) {
        this.internalId = internalId;
    }

    public FridgeItem(Long internalId, Long barcode, Long avg_haltbarkeit, Long times_changed, String name) {
        this.internalId = internalId;
        this.barcode = barcode;
        this.avg_haltbarkeit = avg_haltbarkeit;
        this.times_changed = times_changed;
        this.name = name;
    }

    public Long getInternalId() {
        return internalId;
    }

    public void setInternalId(Long internalId) {
        this.internalId = internalId;
    }

    public Long getBarcode() {
        return barcode;
    }

    public void setBarcode(Long barcode) {
        this.barcode = barcode;
    }

    public Long getAvg_haltbarkeit() {
        return avg_haltbarkeit;
    }

    public void setAvg_haltbarkeit(Long avg_haltbarkeit) {
        this.avg_haltbarkeit = avg_haltbarkeit;
    }

    public Long getTimes_changed() {
        return times_changed;
    }

    public void setTimes_changed(Long times_changed) {
        this.times_changed = times_changed;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
