package fridge;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HISTORY.
 */
public class History {

    private long internalId;
    private Long usedWhen;
    private Long usedTil;
    private Long haltbarkeit;

    public History() {
    }

    public History(long internalId, Long usedWhen, Long usedTil, Long haltbarkeit) {
        this.internalId = internalId;
        this.usedWhen = usedWhen;
        this.usedTil = usedTil;
        this.haltbarkeit = haltbarkeit;
    }

    public long getInternalId() {
        return internalId;
    }

    public void setInternalId(long internalId) {
        this.internalId = internalId;
    }

    public Long getUsedWhen() {
        return usedWhen;
    }

    public void setUsedWhen(Long usedWhen) {
        this.usedWhen = usedWhen;
    }

    public Long getUsedTil() {
        return usedTil;
    }

    public void setUsedTil(Long usedTil) {
        this.usedTil = usedTil;
    }

    public Long getHaltbarkeit() {
        return haltbarkeit;
    }

    public void setHaltbarkeit(Long haltbarkeit) {
        this.haltbarkeit = haltbarkeit;
    }

}
