package fridge;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IN_FRIDGE.
 */
public class InFridge {

    private long internalId;
    private Long inserted;
    private Long expire;
    private Integer anzahl;

    public InFridge() {
    }

    public InFridge(long internalId, Long inserted, Long expire, Integer anzahl) {
        this.internalId = internalId;
        this.inserted = inserted;
        this.expire = expire;
        this.anzahl = anzahl;
    }

    public long getInternalId() {
        return internalId;
    }

    public void setInternalId(long internalId) {
        this.internalId = internalId;
    }

    public Long getInserted() {
        return inserted;
    }

    public void setInserted(Long inserted) {
        this.inserted = inserted;
    }

    public Long getExpire() {
        return expire;
    }

    public void setExpire(Long expire) {
        this.expire = expire;
    }

    public Integer getAnzahl() {
        return anzahl;
    }

    public void setAnzahl(Integer anzahl) {
        this.anzahl = anzahl;
    }

}
